---
- hosts: all
  become: true
  gather_facts: yes

  pre_tasks:

    # FEDORA: use raw dnf instead of Ansible's dnf/package (libdnf5 workaround)
    - name: Install updates for Fedora (workaround libdnf5 issue)
      tags: always, fedora
      ansible.builtin.shell: dnf -y upgrade
      when: ansible_distribution == 'Fedora'

    # UBUNTU: normal apt upgrade
    - name: Install updates for Ubuntu
      tags: always, ubuntu
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'


- hosts: ubuntu
  become: true
  tasks:

    - name: Install apache on web web_servers
      tags: apache, ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_distribution == 'Ubuntu'


- hosts: fedora
  tags: db, fedora
  become: true
  tasks:

    - name: Install mariadb on db_servers (Fedora, libdnf5 workaround)
      ansible.builtin.shell: dnf -y install mariadb
      when: ansible_distribution == 'Fedora'