---
- name: Install developer tools on Windows
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows

  tasks:
    - name: Install specific Python version
      win_chocolatey:
        name: python
        version: 3.10.11
        state: present

    - name: Install Git
      win_chocolatey:
        name: git
        state: present

    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode.install
        state: present

    - name: Install Docker Desktop
      win_chocolatey:
        name: docker-desktop
        state: present