---
- name: Install Chocolatey on Windows
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows

  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present